# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HaloMedals.io
email: info@halomedals.io
description: Review the medals you earned after each Halo 5 guardians match.
baseurl: "/halo-medals" # the subpath of your site, e.g. /blog
url: "http://destefanis.github.io/" # the base hostname & protocol for your site
gamertag: shesjustaglitch
github_username:  destefanis

# Build settings
markdown: kramdown
